type: drupal11
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.8"
fail_on_hook_fail: true
hooks:
    post-start:
        - composer: install
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - PLATFORM_PROJECT=TODO
    - PLATFORM_ENVIRONMENT=main
corepack_enable: true
